### ISSUE TITLE
Roboto instrukcijų failas

### ISSUE THREAD

**Issue by sirex** [aidiss/opendatagovlt#16]
Duomenų šaltinių, iš kurių duomenis gali surinkti duomenų robotai, yra be galo daug. Tam tikros grupės duomenų šaltinių duomenis pateikia panašiu pavidalu, todėl vietoj to, kad kiekvienam duomenų šaltiniui būtų kuriamas naujas robotas, programuojant jį Python kalba, galima susikurti DSL ([Domain-specific language](http://en.wikipedia.org/wiki/Domain-specific_language)).

Deklaratyvus DSL padeda žymiai paprasčiau spręsti konkrečias problemas. Todėl turinti DSL skirtą roboto instrukcijų aprašymui, duomenis iš naujų šaltinių surinkti bus žymiai paprasčiau.

Štai pavyzdys, kaip galėtų atrodyti robotų instrukcijų failas YAML formatu:

``` yaml
name: opendata.gov.lt
crowler:
  start-urls:
    - http://opendata.gov.lt/index.php?vars=/public/public/search
  download-urls:
    - name: table
      pattern: http://opendata\.gov\.lt/index\.php\?vars=/public/public/search/\d+/
      actions: [follow, download]
    - name: details
      pattern: http://opendata\.gov\.lt/index.php\?vars=/public/public/print/\d+/
      actions: [download]
scraper:
  - name: dataset
    source: details
    parser: html-table-fields
    xpath: /html/body/table
    primary-key: [code]
    fields:
      - name: code
        type: integer
        match: Kodas
```

Pagal šitą aprašą bus sukurtos trys duomenų saugyklos, iš kurių `table` ir `details` saugos atsiųstus puslapius, o `dataset` saugos struktūruotus duomenis išrinktus iš `details` duomenų.

Žodžiu, taip gan paprastai galima aprašyti instrukcijas robotui, imti duomenis iš tam tikro šaltinio ir išgauti iš to šaltinio normalizuotus ir struktūruotus duomenis.
