### ISSUE TITLE
Puslapiuose aptinkamos nuorodos į kituose domainuose esančias rinkmenas

### ISSUE THREAD

**Issue by aidiss** [aidiss/opendatagovlt#17]
Kaip elgtis tokiais atvejais?
pvz: 
- cpva nukreipia i ppplietuva 
- neigaliuju informacijos centras nukreipia i lrs.lt

**Comment by sirex** [comment]
Tą sprendžia [duomenų surinkimo robotas (Crawler)](https://github.com/aidiss/opendatagovlt/issues/14). Štai pavyzdys iš [roboto instrukcijų failo](https://github.com/aidiss/opendatagovlt/issues/16), kur būtent aprašyta, kurias nuorodas lankyti, o kurių ne:

``` yaml
name: opendata.gov.lt
crowler:
  start-urls:
    - http://opendata.gov.lt/index.php?vars=/public/public/search
  download-urls:
    - name: table
      pattern: http://opendata\.gov\.lt/index\.php\?vars=/public/public/search/\d+/
      actions: [follow, download]
    - name: details
      pattern: http://opendata\.gov\.lt/index.php\?vars=/public/public/print/\d+/
      actions: [download]
```

Čia pavyzdys yra su opendata.gov.lt svetaine. Tačiau principas yra toks, kad `pattern` lauke yra įrašyta nuorodos regular expression, o `action` nurodo, ką robotas turi daryti aptikęs tokią nuorodą. Kol kas `action` laukas turi du variantus: `download` - atsiųsti nuorodos turinį ir išsaugoti į [duomenų saugyklą](https://github.com/aidiss/opendatagovlt/issues/13), `follow` - analizuoti šio puslapio nuorodas ir pagal tą patį algoritmą spręsti ką daryti su kiekvieną iš aptiktų nuorodų.

**Comment by aidiss** [comment]
1. Ar esame tikri, jog nepasitaikys atvejų, kai kitame puslapyje pateikti duomenys bus svarbu?
2. Svarbiau, galbūt tai, jog ten yra nuorodos, yra svarbi informacija. Gal galime išsaugoti faktą, kad yra nuoroda į duoomenis, saugomus kitame puslapyje?

**Comment by sirex** [comment]
Pateiktame roboto instrukcijų failo pavyzdyje, `download-urls` parametras leidžia aprašyti Regex'ą bet kokiam puslapiui.

Pavyzdžiui:

``` yaml
  download-urls:
    - name: data
      pattern: .*
      actions: [follow, download]
```

Reiškia, kad siųsti absoliučiai visus puslapius.

Žodžiu, yra visiška laisvė aprašyti kas bus siunčiama.
